jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        CO\EShopBundle\Entity\AdminUser:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        CO\EShopBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    providers:
        entity_admin:
            entity:
                class: CO\EShopBundle\Entity\AdminUser
                property: username
        entity_members:
            entity:
                class: COEShopBundle:User
                property: email

    firewalls:
        admin_secured_area:
            pattern: /admin/.*
            provider: entity_admin
            anonymous: ~
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
            logout:
                path:   /admin/logout
                target: /admin/
        members_secured_area:
            #pattern: /members/.*
            pattern: /.*
            provider: entity_members
            anonymous: ~
            form_login:
                check_path: /members/login_check
                login_path: /members/login
            logout:
                path:   /members/logout
                target: /				


    access_control:
        admin_login:
            path: /admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        admin_area:
            path: /admin/.*
            roles: ROLE_ADMIN
        members_login:
            path: /members/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        members_register:
            path: /members/register
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        members_forgot_pass:
            path: /members/forgot_pass
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        members_cart:
            path: /members/cart/.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        home:
            path: /termeni
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        members_area:
            path: /members/.*
            roles: ROLE_USER
