   
#login:
#    pattern:   /security/login
#    defaults:  { _controller: COEShopBundle:Security:login }

admin_login_check:
    pattern:   /admin/login_check

admin_logout:
    pattern:   /admin/logout
    
members_login_check:
    pattern:   /members/login_check
    
members_logout:
    pattern:   /members/logout
    
#logout:
#    pattern:   /security/logout    

_welcome:
    pattern:   /
    defaults:  { _controller: COEShopBundle:Page:home }

COEShopBundle_catalog:        
    resource: "@COEShopBundle/Controller/CatalogController.php"
    prefix:   /
    type:     annotation

COEShopBundle_page:        
    resource: "@COEShopBundle/Controller/PageController.php"
    prefix:   /
    type:     annotation

# --------- admin pages ----------------
COEShopBundle_admin_category:        
    resource: "@COEShopBundle/Controller/AdminCategoryController.php"
    prefix:   /
    type:     annotation

COEShopBundle_admin_product:        
    resource: "@COEShopBundle/Controller/AdminProductController.php"
    prefix:   /
    type:     annotation

COEShopBundle_admin_order:        
    resource: "@COEShopBundle/Controller/AdminOrderController.php"
    prefix:   /
    type:     annotation

COEShopBundle_admin_banner:
    resource: "@COEShopBundle/Controller/AdminBannerController.php"
    prefix:   /
    type:     annotation

COEShopBundle_admin_promo:
    resource: "@COEShopBundle/Controller/AdminPromoController.php"
    prefix:   /
    type:     annotation

COEShopBundle_admin_discount:
    resource: "@COEShopBundle/Controller/AdminDiscountController.php"
    prefix:   /
    type:     annotation

COEShopBundle_admin_cattype:
    resource: "@COEShopBundle/Controller/AdminCatTypeController.php"
    prefix:   /
    type:     annotation

COEShopBundle_admin_users:
    resource: "@COEShopBundle/Controller/AdminUsersController.php"
    prefix:   /
    type:     annotation

COEShopBundle_admin_statistics:
    resource: "@COEShopBundle/Controller/AdminStatisticsController.php"
    prefix:   /
    type:     annotation

COEShopBundle_admin_transfer:
    resource: "@COEShopBundle/Controller/AdminTransferController.php"
    prefix:   /
    type:     annotation

COEShopBundle_admin_shipping:
    resource: "@COEShopBundle/Controller/AdminShippingController.php"
    prefix:   /
    type:     annotation

COEShopBundle_articles:
    resource: "@COEShopBundle/Controller/AdminArticleController.php"
    prefix:   /
    type:     annotation

COEShopBundle_pages:
    resource: "@COEShopBundle/Controller/AdminPagesController.php"
    prefix:   /
    type:     annotation

COEShopBundle_sitevars:
    resource: "@COEShopBundle/Controller/AdminSiteVarsController.php"
    prefix:   /
    type:     annotation

COEShopBundle_mailtemplates:
    resource: "@COEShopBundle/Controller/AdminMailTemplatesController.php"
    prefix:   /
    type:     annotation

COEShopBundle_newsletters:
    resource: "@COEShopBundle/Controller/AdminNewslettersController.php"
    prefix:   /
    type:     annotation
# ============= END admin pages ========================

COEShopBundle_subscribers:
    resource: "@COEShopBundle/Controller/SubscriberController.php"
    prefix:   /
    type:     annotation

COEShopBundle_admin:
    resource: "@COEShopBundle/Controller/AdminController.php"
    prefix:   /
    type:     annotation

COEShopBundle_test:
    resource: "@COEShopBundle/Controller/TestController.php"
    prefix:   /
    type:     annotation

COEShopBundle_members:
    resource: "@COEShopBundle/Controller/MembersController.php"
    prefix:   /
    type:     annotation

COEShopBundle_cart:
    resource: "@COEShopBundle/Controller/CartController.php"
    prefix:   /
    type:     annotation

COEShopBundle_sitemaps:
    resource: "@COEShopBundle/Controller/SitemapsController.php"
    prefix:   /
    type:     annotation

#COEShopBundle_security:
#    resource: "@COEShopBundle/Controller/SecurityController.php"
#    prefix:   /
#    type:     annotation
