<?php

namespace CO\EShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
	
    public function getItems($status)
    {
		$crit = array();
		if ($status<>0) {
			$crit = array('status'=>$status);
		}
		
        return $this->findBy($crit, array('id' => 'DESC'));
    }	
	
}
