<?php

namespace CO\EShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
	const PAG_HOME = '_home';
	const PAG_CONTACT = '_contact';
	const PAG_TERMS = '_terms';
	const PAG_LINKS = "_links";
	const PAG_PPROTECTIA = "_protectia";
}