<?php

namespace CO\EShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteVarRepository extends EntityRepository
{
	public function getCustomValue($var_key) {
		return $this->findOneByName( $var_key )->getContent();
	}
}